name: CMake

on:
  push:
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install Seastar
      run: |
        git clone https://github.com/scylladb/seastar.git
        cd seastar/
        sudo ./install-dependencies.sh
        ./configure.py --mode=release
        ninja -C build/release
        ./configure.py --mode=release --prefix=/usr/local
        sudo ninja -C build/release install

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_PREFIX_PATH="${{github.workspace}}/seastar/build/release;${{github.workspace}}/seastar/build/release/_cooking/installed" -DCMAKE_MODULE_PATH="${{github.workspace}}/seastar/cmake"

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Clippy
      working-directory: ${{github.workspace}}/rust
      run: cargo clippy
